config/routes.rb
Rails.application.routes.draw do

  get 'students/library_list'
  get 'students/books'
  post 'students/history_request', to: 'students#history_request', as: :students_history_request
  post 'students/bookmark', to: 'students#bookmark', as: :students_bookmark
  post 'students/book_return', to: 'students#book_return', as: :students_book_return
  post 'students/delete_reservation', to: 'students#book_delete_reservation', as: :students_book_delete_reservation

  get 'admin/index'
  resources :libraries
  resources :books

  get 'books/index'
  get 'books/delete'
  post 'books/delete'
  get 'books/show'
  get 'books/edit'
  get 'books/show'
  post 'books/show'

  get 'libraries/edit'
  get 'libraries/index'
  get 'libraries/new'
  get 'libraries/delete'
  post 'libraries/delete'
  post '/sessions/create'
  get 'sessions/destroy'

  post 'login/new'
  get 'login/index'
  post 'login/index'
  post 'login/search'

  get 'admins/index'
  get 'admins/login'
  post 'admins/login'
  get 'admins/users'
  get 'admins/delete'
  post 'admins/delete'
  get 'admins/approval'
  post 'admins/approval'
  get 'admins/approved'
  post 'admins/approved'
  get 'admins/:id/edit', to: "admins#edit", as: :admins_profile_edit
  post 'admins/:id', to: "admins#update", as: :admins_profile_update
  get 'admins/books_on_hold'
  get 'admins/checked'
  get 'admins/borrow_history'
  get 'admins/overdue'

  get 'students/show/:id', to: 'students#admin_show', as: :admin_show
  post 'students/:id', to: 'students#admin_update', as: :admin_update

  get 'admins/:id/admin_edit_librarian', to: 'admins#admin_edit_librarian', as: :admin_edit_librarian
  get 'librarians/show/:id', to: 'librarians#admin_show_librarian', as: :admin_show_librarian
  post 'librarians/:id', to: 'librarians#admin_update_librarian', as: :admin_update_librarian

  get 'librarians/new'
  get 'librarians/:id/edit', to: 'librarians#edit', as: :librarian_edit
  post 'librarians/:id', to: 'librarians#update', as: :librarian_update
  get 'librarians/login'
  post 'librarians/login'
  get 'librarians/index'
  post 'librarians/index'
  get 'librarians/books'
  post 'librarians/books'
  get 'librarians/show'
  post 'librarians/show'
  post 'librarians/destroy'
  get 'librarians/checkedout_request', to: 'librarians#checkedout_request', as: :librarians_checkedout_request
  get 'librarians/borrow', to: 'librarians#borrow', as: :librarians_borrow
  get 'librarians/fine', to: 'librarians#fine', as: :librarians_fine

  get 'students/index'
  post 'students/create'
  post 'students/index'
  get 'students/login'
  post 'students/login'
  get 'students/delete'
  post 'students/delete'
  get 'students/:id/edit', to: 'students#edit', as: :student_edit
  post 'students/:id', to: 'students#update', as: :student_update
  get 'students/admin_edit'
  post 'students/admin_edit'

  patch 'students/:id', to: 'students#update'
  get 'students/show'

  resources :students
  resources :login
  resources :sessions
  resources :librarians
  resources :libraries
  resources :books
  resources :admins

  root 'login#index'


end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/approval_request.rb
class ApprovalRequest < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord

  validates :isbn, uniqueness: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  #validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates :title , presence: true
  validates :author, presence: true
  validates :language, presence: true
  validates :published, presence: true
  validates :edition, presence: true
 # validates :image, presence: true
  validates :subject, presence: true
  validates :summary, presence: true
  validates :number_available, presence: true
end

app/models/book_request.rb
class BookRequest < ApplicationRecord
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :isbn, uniqueness: {scope: [:isbn, :student_email]}
  def createnewbookmark(books_id,student_email, student_name)
    book = Book.find(books_id)
    obj = Bookmark.new(:isbn => book.isbn , :title => book.title, :author => book.author, :edition => book.edition, :student_name => student_name, :student_email => student_email)
    obj.save
  end
end

app/models/history_request.rb
class HistoryRequest < ApplicationRecord

  def evaluatebooks(isbn)
      totalfine = 0
      @book = Book.where(isbn: isbn).first
      @library = Library.where(university: @book.university, name: @book.library).first
      hist = self.calculatefines(@library.maxdays, @library.fine)
      totalfine = totalfine + hist.fines
      hist.save
    totalfine
  end

  def calculatefines(maxdays,fine)
   if (Time.now - self.updated_at)/86400 > 1

    if self.status == "Checked Out"
     daysdiff = (Time.now - self.updated_at) / 86400

      if daysdiff > maxdays
        self.fines = self.fines + fine
      end
   end
   end
   self
  end

  def checkoutavailability(email,maxbooks)
    HistoryRequest.where(student_email:email, status:'Checked Out').count >= maxbooks
  end

  def setreturn
    self.status = "Returned"
    var_isb = self.isbn
    book_obj = Book.where(isbn:var_isb).first
    book_obj.number_available = book_obj.number_available + 1
    book_obj.number_checkedout= book_obj.number_checkedout - 1
    book_obj.save
    holdreq_obj = HoldRequest.where(isbn: book_obj.isbn).first
    if !holdreq_obj.nil?
      if !book_obj.special
        obj = HistoryRequest.where(isbn: book_obj.isbn, student_email: holdreq_obj.student_email ).first
        obj.status = "Checked Out"
        book_obj.number_available = book_obj.number_available - 1
        book_obj.number_checkedout = book_obj.number_checkedout + 1
        obj.save
      elsif book_obj.special
        obj = HistoryRequest.where(isbn: book_obj.isbn, student_email: holdreq_obj.student_email ).first
        obj.status = "Waiting for Approval"
        book_obj.number_available = book_obj.number_available - 1
        book_obj.number_checkedout = book_obj.number_checkedout + 1
        apprvl = ApprovalRequest.new(:student_email => holdreq_obj.student_email, :isbn => book_obj.isbn, :title => book_obj.title, :author => book_obj.author, :edition => book_obj.edition, :university => book_obj.university)
        obj.save
        apprvl.save
      end
      holdreq_obj.delete
      book_obj.number_holdrequest = book_obj.number_holdrequest - 1
      book_obj.save
    end

    self
  end
end

app/models/hold_request.rb
class HoldRequest < ApplicationRecord

end

app/models/librarian.rb
class Librarian < ApplicationRecord
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } , uniqueness: true, presence: true
  validates :name, presence: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :library, presence: true
  has_secure_password validations: false
end

app/models/library.rb
class Library < ApplicationRecord
end

app/models/login.rb
class Student < ApplicationRecord
has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } , uniqueness: true, presence: true
    validates :name, presence: true
    validates :password, presence: true, length: { minimum: 6 }
    validates :university, presence: true
    has_secure_password
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins/admin_edit_librarian.html.erb
<div class="heading">
  <h1>Edit Librarian</h1></div>
</div>


<div class="msg">
  <ul>
    <% @librarian.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class="forms">
  <%= form_with scope: :librarian, url: admin_update_librarian_path , local: true do |form| %>
    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </p>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>

    <p>
      <%= form.label :library %>
      <%= select("librarian", "library", Library.all.collect{ |c| [ c.name] }) %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/admins/approval.html.erb
<div class="heading">
  <h1> Approve Librarian </h1>
</div>
<br/>

<div class="msg">
  <% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
  <% end %>
</div>
<br>

<h2> Librarian </h2>
<div class="admin">
  <table>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Library</th>
      <th>Status</th>
    </tr>

    <% @approvals.each do |l| %>
      <tr>
        <td><%= l.email %></td>
        <td><%= l.name %></td>
        <td><%= l.library %></td>
        <td><%= link_to 'Approve', admins_approved_path(:lib_email => l.email) %></td>
      </tr>
    <% end %>
  </table>
  <br/>
</div>

app/views/admins/approved.html.erb
<div class="heading">
  <h1> Approved Librarian </h1>
</div>
<br/>

<div class="msg">
  <% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
  <% end %>
</div>
<br>

app/views/admins/books_on_hold.html.erb
<div class="heading">
  <h1>Books - OnHold </h1>
</div>
<br/>

<div class="admin">
  <table>
    <thead>
    <tr>
      <th>ISBN</th>
      <th>Title</th>
      <th>Author</th>
      <th>Edition</th>
      <th>University</th>
      <th>Held By</th>
      <th> Email </th>
        <th></th>
    </tr>
    </thead>
    <% if !@h_requests.nil? then @h_requests.each do |r| %>
      <tbody>
      <tr>
        <td><%= r.isbn %></td>
        <td><%= r.title %></td>
        <td><%= r.author %></td>
        <td><%= r.edition %></td>
        <td><%= r.university %></td>
        <td><%= r.student_name %></td>
        <td><%= r.student_email %></td>
      </tr>
      </tbody>
    <% end %>
    <% end %>
  </table>
  <br/>
</div>

app/views/admins/borrow_history.html.erb
<div class="heading">
  <h1>Borrow History</h1>
</div>
<br/>

<div class="admin">
  <table>
    <thead>
    <tr>
      <th> ISBN </th>
      <th> Library </th>
      <th> Held By</th>
      <th> Email </th>
      <th></th>
    </tr>
    </thead>
    <% if !@borrowbooks.nil? then @borrowbooks.each do |r| %>
        <tbody>
        <tr>
          <td><%= r.isbn %></td>
          <td><%= r.library_name %>
          <td><%= r.student_name %></td>
          <td><%= r.student_email %></td>
        </tr>
        </tbody>
      <% end %>
    <% end %>
  </table>
  <br/>
</div>

app/views/admins/checked.html.erb
<div class="heading">
  <h1>Books - Checked Out </h1>
</div>
<br/>

<div class="admin">
  <table>
    <thead>
    <tr>
      <th>ISBN</th>
      <th> Library </th>
      <th>Student Name</th>
      <th> Student Email</th>
      <th></th>
    </tr>
    </thead>
    <% if !@checkbooks.nil? then @checkbooks.each do |r| %>
      <tbody>
      <tr>
        <td><%= link_to r.isbn, books_show_path(:book_id => r.isbn) %></td>
        <td><%= r.library_name %>
        <td><%= r.student_name %></td>
        <td><%= r.student_email %></td>
      </tr>
      </tbody>
    <% end %>
      <%end %>
  </table>
  <br/>
</div>

app/views/admins/edit.html.erb
<div class="heading">
  <h1> Edit Admin </h1>
</div>

<div class="msg">
  <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
  <% end %>
</div>
<br>

<div class="forms">
  <%= form_with scope: :admin, url: admins_profile_update_path, local: true do |form| %>
    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </p>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>
    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/admins/index.html.erb
<div class="heading">
  <h1> Welcome Admin </h1>
</div>
<p align="right", style="align-content: end; font-family: Arial; font-size: medium" >
  <%=link_to "Edit Profile", admins_profile_edit_path(session[:id]) %>
  <%= link_to "Logout", sessions_destroy_path  %>
</p>

<br/>
<div class="msg">
  <% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
  <% end %>
</div>
<br>

<div class="tab">
  <p align="left">
  <table>
  <tr>
    <th><%= link_to "Impersonate Student? ", students_login_path%> </th>
    <th><%= link_to "Impersonate Librarian?", librarians_login_path %> </th>
    <th><%= link_to "Unapproved Librarian", admins_approval_path %> </th>
    <th><%= link_to "Libraries", libraries_index_url%> </th>
    <th><%= link_to "Books", books_index_url %> </th>
    <th><%= link_to "Users", admins_users_path %> </th>
    <th><%= link_to "Books On Hold", admins_books_on_hold_path %> </th>
    <th><%= link_to "Checked Out Books", admins_checked_path %> </th>
    <th><%= link_to "Overdue Fine", admins_overdue_path %> </th>
  </tr>

</table>
  </p>
  <h2> New Registration? </h2>
  <p class="admin">
    <p align="left"><table>
    <tr>
      <th><%= link_to "New Student Registration", new_student_path%>
      <th><%= link_to "New Librarian Registration", new_librarian_path%>
      <th><%= link_to "Add New Library", new_library_path%>
      <th><%= link_to "Add New Book", new_book_path%>
    </tr>
  </table></p>
  </div>

</div>

app/views/admins/login.html.erb
<div class="heading">
  <h1>Admin Login</h1></div>
</div>

<div class="msg">
  <% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
  <% end %>
</div>
<br>

<div class="forms">

  <%= form_with scope: :sessions, url: sessions_url, local:  true do |f| %>
    <p>
      <%=f.label :email %><br/>
      <%=f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>

    <%= f.submit :Login %><br>
    <br>

  <% end %>
</div>

app/views/admins/new.html.erb
<div class="heading">
  <h1> Staff Registration </h1>
</div>

<div class="msg">
  <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
  <% end %>
</div>
<br>

<div class="forms">
  <%= form_for @admin do |form| %>
    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </p>
    <p>

      <%= form.label :name %><br>
      <%= form.text_field :name %>

    </p>
    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>

    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/admins/overdue.html.erb
<div class="heading">
  <h1> Students With Overdue Fines </h1>
</div>

<div class="admin">
<table >
  <thead>
  <tr>
    <th scope="col">ISBN</th>
    <th scope="col">StudentName</th>
    <th scope="col">Fine</th>
  </tr>
  </thead>

  <tbody>
  <% @finepay.each do |h| %>
    <tr>
      <td><%= h.isbn%></td>
      <td><%= h.student_name %></td>
      <td><%= h.fines %></td>
    </tr>
  <%end %>
  </tbody>
</table>
</div>

app/views/admins/users.html.erb
<div class="heading">
  <h1>Users</h1>
</div>
<br/>

<br>
<div class="msg">
  <% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
  <% end %>
</div>
<br>

<h2> Students </h2>
<div class="admin">
  <table>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Education</th>
      <th>University</th>
      <th>Show</th>
      <th>Delete</th>
    </tr>

    <% @students.each do |s| %>
      <tr>
        <td><%= s.email %></td>
        <td><%= s.name %></td>
        <td><%= s.education %></td>
        <td><%= s.university %></td>
        <td><%= link_to 'Show', admin_show_path(s) %></td>
        <td><%= link_to 'Destroy', admins_delete_path(:student_id => s.id) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
  <br/>
</div>

<h2> Librarian </h2>
<div class="admin">
  <table>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Library</th>
      <th>Show</th>
      <th>Delete</th>
    </tr>

    <% @librarians.each do |l| %>
      <tr>
        <td><%= l.email %></td>
        <td><%= l.name %></td>
        <td><%= l.library %></td>
        <td><%= link_to 'Show', admin_show_librarian_path(l) %></td>
        <td><%= link_to 'Destroy', admins_delete_path(:lib_id => l.id) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
  <br/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigitalLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>