config/routes.rb
Rails.application.routes.draw do

  get 'students/library_list'
  get 'students/books'
  post 'students/history_request', to: 'students#history_request', as: :students_history_request
  post 'students/bookmark', to: 'students#bookmark', as: :students_bookmark
  post 'students/book_return', to: 'students#book_return', as: :students_book_return
  post 'students/delete_reservation', to: 'students#book_delete_reservation', as: :students_book_delete_reservation

  get 'admin/index'
  resources :libraries
  resources :books

  get 'books/index'
  get 'books/delete'
  post 'books/delete'
  get 'books/show'
  get 'books/edit'
  get 'books/show'
  post 'books/show'

  get 'libraries/edit'
  get 'libraries/index'
  get 'libraries/new'
  get 'libraries/delete'
  post 'libraries/delete'
  post '/sessions/create'
  get 'sessions/destroy'

  post 'login/new'
  get 'login/index'
  post 'login/index'
  post 'login/search'

  get 'admins/index'
  get 'admins/login'
  post 'admins/login'
  get 'admins/users'
  get 'admins/delete'
  post 'admins/delete'
  get 'admins/approval'
  post 'admins/approval'
  get 'admins/approved'
  post 'admins/approved'
  get 'admins/:id/edit', to: "admins#edit", as: :admins_profile_edit
  post 'admins/:id', to: "admins#update", as: :admins_profile_update
  get 'admins/books_on_hold'
  get 'admins/checked'
  get 'admins/borrow_history'
  get 'admins/overdue'

  get 'students/show/:id', to: 'students#admin_show', as: :admin_show
  post 'students/:id', to: 'students#admin_update', as: :admin_update

  get 'admins/:id/admin_edit_librarian', to: 'admins#admin_edit_librarian', as: :admin_edit_librarian
  get 'librarians/show/:id', to: 'librarians#admin_show_librarian', as: :admin_show_librarian
  post 'librarians/:id', to: 'librarians#admin_update_librarian', as: :admin_update_librarian

  get 'librarians/new'
  get 'librarians/:id/edit', to: 'librarians#edit', as: :librarian_edit
  post 'librarians/:id', to: 'librarians#update', as: :librarian_update
  get 'librarians/login'
  post 'librarians/login'
  get 'librarians/index'
  post 'librarians/index'
  get 'librarians/books'
  post 'librarians/books'
  get 'librarians/show'
  post 'librarians/show'
  post 'librarians/destroy'
  get 'librarians/checkedout_request', to: 'librarians#checkedout_request', as: :librarians_checkedout_request
  get 'librarians/borrow', to: 'librarians#borrow', as: :librarians_borrow
  get 'librarians/fine', to: 'librarians#fine', as: :librarians_fine

  get 'students/index'
  post 'students/create'
  post 'students/index'
  get 'students/login'
  post 'students/login'
  get 'students/delete'
  post 'students/delete'
  get 'students/:id/edit', to: 'students#edit', as: :student_edit
  post 'students/:id', to: 'students#update', as: :student_update
  get 'students/admin_edit'
  post 'students/admin_edit'

  patch 'students/:id', to: 'students#update'
  get 'students/show'

  resources :students
  resources :login
  resources :sessions
  resources :librarians
  resources :libraries
  resources :books
  resources :admins

  root 'login#index'


end

app/models/student.rb
class Student < ApplicationRecord
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } , uniqueness: true, presence: true
    validates :name, presence: true
    validates :password, presence: true, length: { minimum: 6 }
    validates :university, presence: true
    has_secure_password
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def history_request
    flash[:alert] = ""
    bookchangenumber = false
    @student = Student.find(session[:id])
    check = params[:book_ids].nil?
    if !check
      obj = HistoryRequest.new
      checkout_list = params[:book_ids].collect {|id| id.to_i}
      checkout_list.each do |id|
        book = Book.find(id)
        if obj.checkoutavailability(@student.email, @student.maxbook)
          flash[:alert] = "Maximum checkout books already reached!"
          break
        elsif book.number_available > 0 && !book.special
          obj = HistoryRequest.new(:library_name => book.library, :isbn => book.isbn, :status => "Checked Out" , :student_name => @student.name , :student_email => @student.email)
          LibraryMailer.library_mailer(@student).deliver
          obj.save
          bookchangenumber = true
        elsif book.special && book.number_available > 0
          obj = HistoryRequest.new(:library_name => book.library, :isbn => book.isbn, :status => "Waiting for Approval" , :student_name => @student.name , :student_email => @student.email)
          apprvl = ApprovalRequest.new(:student_email => @student.email, :isbn => book.isbn, :title => book.title, :author => book.author, :edition => book.edition, :university => book.university)
          obj.save
          apprvl.save
        elsif book.number_available == 0
          obj = HistoryRequest.new(:library_name => book.library, :isbn => book.isbn, :status => "On Hold" , :student_name => @student.name , :student_email => @student.email)
          book.number_holdrequest = book.number_holdrequest + 1
          holdreq = HoldRequest.new(:student_email => @student.email, :student_name => @student.name, :isbn => book.isbn, :title => book.title, :author => book.author, :edition => book.edition, :university => book.university)
          obj.save
          book.save
          holdreq.save
          flash[:alert] = "Book sent to Hold request. Please wait till books are returned."
        end
        if bookchangenumber == true
          book.number_available = book.number_available - 1
          book.number_checkedout = book.number_checkedout + 1
          book.save
        end
      end
      end
    @hist_req = HistoryRequest.where(student_email:@student.email).order(updated_at: :desc)
  end

  def new
    @student = Student.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  def index
    @student = Student.find(session[:id])
    @bookmark = Bookmark.where(student_email: @student.email)
    @history_request = HistoryRequest.where(student_email: @student.email)
    totalfine = 0
    if !@history_request.nil?
      @history_request.each do |hist|
        totalfine = totalfine + hist.evaluatebooks(hist.isbn)
      end
    end
      @history_request_totalfines = HistoryRequest.new(:fines => totalfine)
      @history_request = HistoryRequest.where(student_email: @student.email).where('fines > 0')
      render 'students/index'
    end

  def library_list
    @libraries = Library.all
  end
  def books
    @books = Book.all
    @student = Student.find(session[:id])
  end

  def bookmark
    render "students/bookmark"
  end

  def show
    @student = Student.find(session[:id])
    my_render_type = params[:type]
    if my_render_type == "history_request"
      @hist_req = HistoryRequest.where(student_email:@student.email).order(updated_at: :desc)
      render "students/history_request"
    elsif my_render_type == "bookmark"
      books_id = params[:book_id].to_i
      bookmark = Bookmark.new
      bookmark.createnewbookmark(books_id,@student.email, @student.name)
      redirect_to students_books_path(type: "books")
    elsif my_render_type == "book_return"
        hist_id = params[:hist_id].to_i
        histreq_obj = HistoryRequest.find(hist_id)
        histreq_obj.setreturn
        histreq_obj.save
        redirect_to students_books_path(type: "history_request")
    elsif my_render_type == "delete_reservation"
      hist_id = params[:hist_id].to_i
      histreq_obj = HistoryRequest.find(hist_id)
      if histreq_obj.status == "Waiting for Approval"
        apprvl_obj = ApprovalRequest.where(:student_email => @student.email, :isbn => histreq_obj.isbn).first
        apprvl_obj.destroy
      end
      histreq_obj.destroy
      book_obj = Book.where(:isbn => histreq_obj.isbn).first
      book_obj.number_holdrequest = book_obj.number_holdrequest - 1
      book_obj.save
      redirect_to students_books_path(type: "history_request")
      else
      render "students/index" #EDIT THIS!!
    end
  end

  def create
    @student = Student.new(student_params)
    if @student.education == "undergrad"
      @student.maxbook = 2
    elsif @student.education == "grad"
      @student.maxbook = 4
    elsif @student.education == "phd"
      @student.maxbook = 6
    else
      @student.maxbook = 2
    end
    if @student.save
      redirect_to students_login_url, alert: "Registration Successful, Please login!!"
    else
      redirect_to new_student_path, alert: "OOPS!! Problem Occurred. Please enter details again!"
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @bookmark = Bookmark.where(student_email: @student.email)
    @history_request = HistoryRequest.where(student_email: @student.email)
    totalfine = 0
    if !@history_request.nil?
      @history_request.each do |hist|
        totalfine = totalfine + hist.evaluatebooks(hist.isbn)
      end
    end
    @history_request_totalfines = HistoryRequest.new(:fines => totalfine)
    @history_request = HistoryRequest.where(student_email: @student.email).where('fines > 0')

    respond_to do |format|
      if @student.update(email: params[:student][:email], name: params[:student][:name], password: params[:student][:password])
        format.html { render 'students/index', alert: 'Student successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to admins_allstudents_path}
      format.json { head :no_content }
    end
  end



  def admin_edit
    @student = Student.find(params[:id])
  end

  def admin_show
    @student = Student.find(params[:id])
  end

  def admin_update
    @student = Student.find(params[:id])
    respond_to do |format|
      if @student.update(email: params[:student][:email], name: params[:student][:name],
                         password: params[:student][:password],
                         education: params[:student][:education],
                         university: params[:student][:education]
      )
        format.html { redirect_to admins_users_path, alert: 'Student successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def student_params
    params.require(:student).permit(:email, :name, :password, :education, :university)
  end
  end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="msg">
<ul>
  <% @student.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
</div>

<div class="forms">
  <%= form_for @student do |form| %>

    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </p>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>

    <p>
      <%= form.label :education %><br>
      <%= form.radio_button :education, 'UnderGrad', :checked => true %>
      <%= form.label :undergrad, 'UnderGraduate' %>
      <%= form.radio_button :education, 'Graduate' %>
      <%= form.label :graduate, 'Graduate' %>
      <%= form.radio_button :education, 'PhD' %>
      <%= form.label :phd, 'PhD' %>
    </p>

    <p>
      <%= form.label :university %><br>
      <%= select("student", "university", Library.all.collect{ |c| [ c.university] }) %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/students/admin_edit.html.erb
<div class="heading">
  <h1>Edit Student</h1></div>
</div>

<div class="msg">
  <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class="forms">
  <%= form_with scope: :student, url: admin_update_path, local: true do |form| %>
    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </p>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>

    <p>
      <%= form.label :education %><br>
      <%= form.radio_button :education, 'undergrad', :checked => true %>
      <%= form.label :undergrad, 'UnderGraduate' %>
      <%= form.radio_button :education, 'graduate' %>
      <%= form.label :graduate, 'Graduate' %>
      <%= form.radio_button :education, 'phd' %>
      <%= form.label :phd, 'PhD' %>
    </p>

    <p>
      <%= form.label :university %><br>
      <%= form.text_field :university %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/students/admin_show.html.erb
<div class="heading">
  <h1>Student Profile </h1>
</div>

<div class="msg">
  <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
  <% end %>
</div>
<br>

<div class="msg">
  <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class="forms">
  <%= form_for @student do |form| %>

    <p>
      <%= form.label :email %><br>
      <%= @student.email %>
    </p>

    <p>
      <%= form.label :name %><br>
      <%= @student.name %>
    </p>

    <p>
      <%= form.label :education %><br>
      <%= @student.education %>
    </p>

    <p>
      <%= form.label :university %><br>
      <%= @student.university %>
    </p>

  <% end %>
</div>

app/views/students/book_return.html.erb
<h1>Book returned!</h1>

app/views/students/bookmark.html.erb
<h1>bookmarked</h1>

app/views/students/books.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Students Landing Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Digital Library</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", students_path %></li>
      <li><%= link_to "Libraries", students_library_list_path(type: "library_list")%></li>
      <li><%= link_to "Books", students_books_path(type: "books") %></li>
      <li><%= link_to "Checkout History", students_history_request_path(type: "history_request") %></li>
      <li><%= link_to "Logout", sessions_destroy_path %></li>
    </ul>
  </div>
</nav>
<div class="container">
  <input class='form-control' id='myInput' type='text' placeholder='Search for book based on attributes from table'>
  <%= form_tag students_history_request_path do %>
    <table class='table table-striped'>
      <thead>
      <tr>
        <th scope="col">ISBN</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Language</th>
        <th scope="col">Published</th>
        <th scope="col">Edition</th>
        <th scope="col">Image</th>
        <th scope="col">Subject</th>
        <th scope="col">Summary</th>
        <th scope="col">Special?</th>
        <th scope="col">Available</th>
        <th scope="col"> Hold Requests</th>
        <th data-sort-ignore="true">Checkout</th>
        <th scope="col">Bookmark</th>
      </tr>
      </thead>
      <tbody id="myTable">
      <%= if !@books.nil? then @books.each do |book| %>
          <tr>
            <td><%= book.isbn %></td>
            <td><%= book.title%></td>
            <td><%= book.author %></td>
            <td><%= book.language %></td>
            <td><%= book.published %></td>
            <td><%= book.edition %></td>
            <td><%= image_tag book.image.url(:thumb) %></td>
            <td><%= book.subject %></td>
            <td><%= book.summary %></td>
            <td><%= book.special %></td>
            <td><%= book.number_available %></td>
            <td><%= book.number_holdrequest %></td>
            <%if book.university == @student.university %>
            <td><%= check_box_tag "book_ids[]", book.id, false, class: 'selectable' %>
            </td>
              <%else %>
              <td></td>
              <%end %>
            <td><%= link_to students_bookmark_path(type: "bookmark", :book_id => book.id) do %>
                <button>BookMark</button>
              <% end %></td>
          </tr>
        <% end %>
      <% end %>
  <% end %>
  </tbody>
  </table>
  </form>
  <%= submit_tag "check out", :class => 'btn btn-primary btn-xs' %>
  <script>
      $(document).ready(function(){
          $("#myInput").on("keyup", function() {
              var value = $(this).val().toLowerCase();
              $("#myTable tr").filter(function() {
                  $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
              });
          });
      });
  </script>
</div>
</body>
</html>

app/views/students/edit.html.erb
<div class="heading">
  <h1>Edit Student</h1></div>
</div>

<div class="msg">
  <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class="forms">
  <%= form_for @student do |form| %>

    <p>
      <%= form.label :emaill %><br>
      <%= form.text_field :email %>
    </p>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/students/history_request.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Students Landing Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Digital Library</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", students_path %></li>
      <li><%= link_to "Libraries", students_library_list_path(type: "library_list")%></li>
      <li><%= link_to "Books", students_books_path(type: "books") %></li>
      <li><%= link_to "Checkout History", students_history_request_path(type: "history_request") %></li>
      <li><%= link_to "Logout", sessions_destroy_path %></li>
    </ul>
  </div>
</nav>

<div class="container">
  <% if flash[:alert] %>
    <h1><%= flash[:alert] %></h1>
  <% end %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">Library</th>
      <th scope="col">ISBN</th>
      <th scope="col">Status</th>
      <th scope="col">Time Checked out</th>
      <th scope="col">Return</th>
      <th scope="col">Delete Reservation</th>
    </tr>
    </thead>
    <tbody>
    <% if !@hist_req.nil? then @hist_req.each do |hist| %>
        <tr>
          <td><%= hist.library_name %></td>
          <td><%= hist.isbn%></td>
          <td><%= hist.status %></td>
          <td><%= hist.updated_at %></td>
          <% if hist.status == "Checked Out" %>
          <td><%= link_to students_book_return_path(type: "book_return", :hist_id => hist.id) do %>
            <button>Return</button>
            <%  end  %></td>
            <%else %>
            <td></td>
            <%end %>
          <% if hist.status == "Waiting for Approval" || hist.status == "On Hold" %>
            <td><%= link_to students_book_delete_reservation_path(type: "delete_reservation", :hist_id => hist.id) do %>
                <button>Delete Reservation</button>
              <%  end  %></td>
          <%else %>
            <td></td>
          <%end %>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>
</body>
</html>

app/views/students/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Students Landing Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Digital Library</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", students_path %></li>
      <li><%= link_to "Libraries", students_library_list_path(type: "library_list")%></li>
      <li><%= link_to "Books", students_books_path(type: "books") %></li>
      <li><%= link_to "Checkout History", students_history_request_path(type: "history_request") %></li>
      <li><%= link_to "Logout", sessions_destroy_path %></li>
    </ul>
  </div>
</nav>
<div class="container">
  <p align="right"><%= link_to "Edit Profile", edit_student_path(@student) %> </p>
  <div class="container">
    <table class="table table-striped">
      <caption>Books Bookmarked</caption>
      <thead>
      <tr>
        <th scope="col">ISBN</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Edition</th>
      </tr>
      </thead>
      <tbody>
      <% if !@bookmark.nil? then @bookmark.each do |book| %>
          <tr>
            <td><%= book.isbn %></td>
            <td><%= book.title%></td>
            <td><%= book.author %></td>
            <td><%= book.edition %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="container">
    <pre>
    <h2> <%="Total Fines Due:" + @history_request_totalfines.fines.to_s %></h2>
    </pre>
    <table class="table table-striped">
      <caption>List of Fines</caption>
      <thead>
      <tr>
        <th scope="col">Library</th>
        <th scope="col">ISBN</th>
        <th scope="col">Status</th>
        <th scope="col">Time Checked out</th>
        <th scope="col">Fine</th>
      </tr>
      </thead>
      <tbody>
      <% if !@history_request.nil? then @history_request.each do |hist| %>
          <tr>
            <td><%= hist.library_name %></td>
            <td><%= hist.isbn%></td>
            <td><%= hist.status %></td>
            <td><%= hist.updated_at %></td>
            <td><%= hist.fines %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>

</div>
</body>
</html>

app/views/students/library_list.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Students Landing Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Digital Library</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", students_path %></li>
      <li><%= link_to "Libraries", students_library_list_path(type: "library_list")%></li>
      <li><%= link_to "Books", students_books_path(type: "books") %></li>
      <li><%= link_to "Checkout History", students_history_request_path(type: "history_request") %></li>
      <li><%= link_to "Logout", sessions_destroy_path %></li>
    </ul>
  </div>
</nav>

<div class="container">
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">University</th>
      <th scope="col">Location</th>
      <th scope="col">Max days a book issued</th>
    </tr>
    </thead>
   <tbody>
    <% if !@libraries.nil? then @libraries.each do |library| %>
    <tr>
      <td><%= library.name %></td>
      <td><%= library.university%></td>
      <td><%= library.location %></td>
      <td><%= library.maxdays %></td>
    </tr>
      <% end %>
    <% end %>
   </tbody>
  </table>
</div>
</body>
</html>

app/views/students/login.html.erb
<div class="heading">
  <h1>Students Login</h1></div>
</div>

<div class="msg">
  <% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
  <% end %>
</div>
<br>

<div class="forms">

  <%= form_with scope: :sessions, url: sessions_url, local:  true do |f| %>
    <p>
      <%=f.label :email %><br/>
      <%=f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>

    <%= f.submit :Login %><br>
    <br>

    <%= link_to 'New User Please Register here', new_student_path %>
  <% end %>

</div>

app/views/students/new.html.erb
<div class="heading">
  <h1>Student Registration </h1>
</div>

<div class="msg">
  <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
  <% end %>
</div>
<br>


<%= render 'students/form' %>

app/views/students/show.html.erb
<h1>show</h1>
<div class="msg">
  <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
  <% end %>
</div>
<br>