config/routes.rb
Rails.application.routes.draw do

  get 'students/library_list'
  get 'students/books'
  post 'students/history_request', to: 'students#history_request', as: :students_history_request
  post 'students/bookmark', to: 'students#bookmark', as: :students_bookmark
  post 'students/book_return', to: 'students#book_return', as: :students_book_return
  post 'students/delete_reservation', to: 'students#book_delete_reservation', as: :students_book_delete_reservation

  get 'admin/index'
  resources :libraries
  resources :books

  get 'books/index'
  get 'books/delete'
  post 'books/delete'
  get 'books/show'
  get 'books/edit'
  get 'books/show'
  post 'books/show'

  get 'libraries/edit'
  get 'libraries/index'
  get 'libraries/new'
  get 'libraries/delete'
  post 'libraries/delete'
  post '/sessions/create'
  get 'sessions/destroy'

  post 'login/new'
  get 'login/index'
  post 'login/index'
  post 'login/search'

  get 'admins/index'
  get 'admins/login'
  post 'admins/login'
  get 'admins/users'
  get 'admins/delete'
  post 'admins/delete'
  get 'admins/approval'
  post 'admins/approval'
  get 'admins/approved'
  post 'admins/approved'
  get 'admins/:id/edit', to: "admins#edit", as: :admins_profile_edit
  post 'admins/:id', to: "admins#update", as: :admins_profile_update
  get 'admins/books_on_hold'
  get 'admins/checked'
  get 'admins/borrow_history'
  get 'admins/overdue'

  get 'students/show/:id', to: 'students#admin_show', as: :admin_show
  post 'students/:id', to: 'students#admin_update', as: :admin_update

  get 'admins/:id/admin_edit_librarian', to: 'admins#admin_edit_librarian', as: :admin_edit_librarian
  get 'librarians/show/:id', to: 'librarians#admin_show_librarian', as: :admin_show_librarian
  post 'librarians/:id', to: 'librarians#admin_update_librarian', as: :admin_update_librarian

  get 'librarians/new'
  get 'librarians/:id/edit', to: 'librarians#edit', as: :librarian_edit
  post 'librarians/:id', to: 'librarians#update', as: :librarian_update
  get 'librarians/login'
  post 'librarians/login'
  get 'librarians/index'
  post 'librarians/index'
  get 'librarians/books'
  post 'librarians/books'
  get 'librarians/show'
  post 'librarians/show'
  post 'librarians/destroy'
  get 'librarians/checkedout_request', to: 'librarians#checkedout_request', as: :librarians_checkedout_request
  get 'librarians/borrow', to: 'librarians#borrow', as: :librarians_borrow
  get 'librarians/fine', to: 'librarians#fine', as: :librarians_fine

  get 'students/index'
  post 'students/create'
  post 'students/index'
  get 'students/login'
  post 'students/login'
  get 'students/delete'
  post 'students/delete'
  get 'students/:id/edit', to: 'students#edit', as: :student_edit
  post 'students/:id', to: 'students#update', as: :student_update
  get 'students/admin_edit'
  post 'students/admin_edit'

  patch 'students/:id', to: 'students#update'
  get 'students/show'

  resources :students
  resources :login
  resources :sessions
  resources :librarians
  resources :libraries
  resources :books
  resources :admins

  root 'login#index'


end

app/models/book.rb
class Book < ApplicationRecord

  validates :isbn, uniqueness: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  #validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates :title , presence: true
  validates :author, presence: true
  validates :language, presence: true
  validates :published, presence: true
  validates :edition, presence: true
 # validates :image, presence: true
  validates :subject, presence: true
  validates :summary, presence: true
  validates :number_available, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def edit
    bookid = params[:book_id]
    @book = Book.find(bookid)
  end

  def update
    @book = Book.find(params[:id])
    @library = Library.find_by_name(@book.library)
    if !@library.nil?
      @book.university = @library.university
    end
      respond_to do |format|
          if @book.update(isbn: params[:book][:isbn],
                          title: params[:book][:title],
                          author: params[:book][:author],
                          edition: params[:book][:edition],
                          language: params[:book][:language],
                          published: params[:book][:published],
                          subject: params[:book][:subject],
                          summary: params[:book][:summary],
                          special: params[:book][:special],
                          library: params[:book][:library],
                          number_available: params[:book][:number_available],
                          number_checkedout: params[:book][:number_checkedout],
                          number_holdrequest: params[:book][:number_holdrequest])
            format.html { render books_show_path, alert: 'Book was successfully updated.' }
            format.json { head :no_content }
          else
            format.json { render json: @books }
            format.html { render action:"edit" }
            format.json { render json: @book.errors, status: :unprocessable_entity }
          end
        end
  end

  def index
    @books = Book.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @books }
    end
  end

  def new
    @book = Book.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  def create
    @book = Book.new(book_params)
    @library = Library.find_by_name(@book.library)
    @book.university = @library.university
    if @book.save
      redirect_to books_index_url
    else
      redirect_to new_book_path , alert: "Some error occurred"
    end
  end

  def show
    bookid = params[:book_id]
    bookview = params[:id]
    if bookview == "index"
      @books = Book.all
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @books }
      end
      render "books/index"
    elsif bookview == "edit"
    @book = Book.find(bookid)
      render "books/edit"
    else
      @book = Book.find(bookid)
      render "books/show"
  end
  end
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_index_url }
      format.json { head :no_content }
    end
  end

def set_recipe
  @book = Book.find(params[:id])
end

  private
  def book_params
    params.require(:book).permit(:isbn, :title, :author, :language, :published, :edition, :image,
                                 :subject, :summary, :special, :library, :number_available , :number_checkedout,
                                 :number_holdrequest);
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="heading">
  <h1>Edit Book</h1></div>
</div>

<div class="msg">
  <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class="forms">
  <%= form_for @book, html: {multipart: true} do |form| %>
    <p>
      <%= form.label :isbn %><br>
      <%= form.text_field :isbn %>
    </p>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :author %><br>
      <%= form.text_field :author %>
    </p>

    <p>
      <%= form.label :edition %><br>
      <%= form.text_field :edition %>
    </p>

    <p>
      <%= form.label :language %><br>
      <%= form.text_field :language %>
    </p>

    <p>
      <%= form.label :published %><br>
      <%= form.text_field :published %>
    </p>

    <p>
      <%= form.label :subject %><br>
      <%= form.text_field :subject %>
    </p>

    <p>
      <%= form.label :summary %><br>
      <%= form.text_area :summary %>
    </p>

    <p>
      <%= form.label :special %><br>
      <%= form.select :special, ["false", "true"] %>
    </p>

    <p>
      <%= form.label :library %>
      <%= select("book", "library", Library.all.collect{ |c| [ c.name] }) %>
    </p>
    <p>
      <%= form.label :number_avaiable %><br>
      <%= form.text_field :number_available %>
    </p>

    <p>
      <%= form.label :number_checkedout %><br>
      <%= form.text_field :number_checkedout %>
    </p>
    <p>
      <%= form.label :number_holdrequest %><br>
      <%= form.text_field :number_holdrequest %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/books/index.html.erb
<div class="heading">
  <h1>Listing Books</h1>
</div>
<br/>


<div class="admin">
<table>
  <thead>
  <tr>
    <th scope="col">ISBN</th>
    <th scope="col">Title</th>
    <th scope="col">Author</th>
    <th scope="col">Language</th>
    <th scope="col">Published</th>
    <th scope="col">Edition</th>
    <th scope="col">Image</th>
    <th scope="col">Subject</th>
    <th scope="col">Summary</th>
    <th scope="col">Special</th>
    <th scope="col">Library</th>
    <th scope="col">In Stock</th>
    <th scope="col">Show</th>
    <th scope="col">Edit</th>
    <th scope="col">Destroy</th>
    <th scope="col"> History </th>
  </tr>
  </thead>

  <tbody>
  <% if !@books.nil? then @books.each do |book| %>
    <tr>
      <td><%= book.isbn %></td>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.language %></td>
      <td><%= book.published %></td>
      <td><%= book.edition %></td>
      <td><%= image_tag book.image.url(:thumb) %></td>
      <td><%= book.subject %></td>
      <td><%= book.summary %></td>
      <td><%= book.special %></td>
      <td><%= book.library %></td>
      <td><%= book.number_available %></td>
      <td><%= link_to 'Show', books_show_path(:book_id => book.id) %></td>
      <td><%= link_to 'Edit', books_edit_path(:book_id => book.id) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'History', admins_borrow_history_path(:book_isbn => book.isbn) %></td>
    </tr>
  <% end %>
  <% end %>
  </tbody>
</table>
  <%= link_to 'New Book', new_book_path %>
</div>

app/views/books/new.html.erb
<div class="heading">
  <h1> Register Book </h1>
</div>


<div class="msg">
  <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
  <% end %>
</div>
<br>

<div class="forms">
  <%= form_for @book, html: {multipart: true} do |form| %>
    <p>
      <%= form.label :isbn %><br>
      <%= form.text_field :isbn %>
    </p>

    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :author %><br>
      <%= form.text_field :author %>
    </p>

    <p>
      <%= form.label :language %><br>
      <%= form.text_field :language %>
    </p>

    <p>
      <%= form.label :published %><br>
      <%= form.text_field :published %>
    </p>

    <p>
      <%= form.label :edition %><br>
      <%= form.text_field :edition %>
    </p>

    <p>
      <%= form.label :image %><br>
      <%= form.file_field :image %>
    </p>

    <p>
      <%= form.label :subject %><br>
      <%= form.text_field :subject %>
    </p>

    <p>
      <%= form.label :summary %><br>
      <%= form.text_area :summary %>
    </p>

    <p>
      <%= form.label :special %><br>
      <%= form.select :special, ["false", "true"]  %>
    </p>

    <p>
      <%= form.label :library %>
      <%= select("book", "library", Library.all.collect{ |c| [ c.name] }) %>
    </p>

    <p>
      <%= form.label :number_avaiable %><br>
      <%= form.text_field :number_available %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/books/show.html.erb
<div class="heading">
  <h1>Show Book</h1>
</div>

<div class="msg">
  <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
  <% end %>
</div>
<br>

<div class="admin">
<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Language:</strong>
  <%= @book.language %>
</p>

<p>
  <strong>Published:</strong>
  <%= @book.published %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @book.edition %>
</p>

<p>
  <strong>Cover:</strong>
  <%= image_tag @book.image.url(:thumb) %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @book.subject %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @book.summary %>
</p>

<p>
  <strong>Special:</strong>
  <%= @book.special %>
</p>

<p>
  <strong>Library:</strong>
  <%= @book.library %>
</p>

<p>
  <strong>University:</strong>
  <%= @book.university %>
</p>

<p>
  <strong>In Stock:</strong>
  <%= @book.number_available %>
</p>

<p>
  <strong>Checkedout:</strong>
  <%= @book.number_checkedout %>
</p>

<p>
  <strong>Holdrequest:</strong>
  <%= @book.number_holdrequest %>
</p>
</div>