config/routes.rb
Rails.application.routes.draw do

  get 'students/library_list'
  get 'students/books'
  post 'students/history_request', to: 'students#history_request', as: :students_history_request
  post 'students/bookmark', to: 'students#bookmark', as: :students_bookmark
  post 'students/book_return', to: 'students#book_return', as: :students_book_return
  post 'students/delete_reservation', to: 'students#book_delete_reservation', as: :students_book_delete_reservation

  get 'admin/index'
  resources :libraries
  resources :books

  get 'books/index'
  get 'books/delete'
  post 'books/delete'
  get 'books/show'
  get 'books/edit'
  get 'books/show'
  post 'books/show'

  get 'libraries/edit'
  get 'libraries/index'
  get 'libraries/new'
  get 'libraries/delete'
  post 'libraries/delete'
  post '/sessions/create'
  get 'sessions/destroy'

  post 'login/new'
  get 'login/index'
  post 'login/index'
  post 'login/search'

  get 'admins/index'
  get 'admins/login'
  post 'admins/login'
  get 'admins/users'
  get 'admins/delete'
  post 'admins/delete'
  get 'admins/approval'
  post 'admins/approval'
  get 'admins/approved'
  post 'admins/approved'
  get 'admins/:id/edit', to: "admins#edit", as: :admins_profile_edit
  post 'admins/:id', to: "admins#update", as: :admins_profile_update
  get 'admins/books_on_hold'
  get 'admins/checked'
  get 'admins/borrow_history'
  get 'admins/overdue'

  get 'students/show/:id', to: 'students#admin_show', as: :admin_show
  post 'students/:id', to: 'students#admin_update', as: :admin_update

  get 'admins/:id/admin_edit_librarian', to: 'admins#admin_edit_librarian', as: :admin_edit_librarian
  get 'librarians/show/:id', to: 'librarians#admin_show_librarian', as: :admin_show_librarian
  post 'librarians/:id', to: 'librarians#admin_update_librarian', as: :admin_update_librarian

  get 'librarians/new'
  get 'librarians/:id/edit', to: 'librarians#edit', as: :librarian_edit
  post 'librarians/:id', to: 'librarians#update', as: :librarian_update
  get 'librarians/login'
  post 'librarians/login'
  get 'librarians/index'
  post 'librarians/index'
  get 'librarians/books'
  post 'librarians/books'
  get 'librarians/show'
  post 'librarians/show'
  post 'librarians/destroy'
  get 'librarians/checkedout_request', to: 'librarians#checkedout_request', as: :librarians_checkedout_request
  get 'librarians/borrow', to: 'librarians#borrow', as: :librarians_borrow
  get 'librarians/fine', to: 'librarians#fine', as: :librarians_fine

  get 'students/index'
  post 'students/create'
  post 'students/index'
  get 'students/login'
  post 'students/login'
  get 'students/delete'
  post 'students/delete'
  get 'students/:id/edit', to: 'students#edit', as: :student_edit
  post 'students/:id', to: 'students#update', as: :student_update
  get 'students/admin_edit'
  post 'students/admin_edit'

  patch 'students/:id', to: 'students#update'
  get 'students/show'

  resources :students
  resources :login
  resources :sessions
  resources :librarians
  resources :libraries
  resources :books
  resources :admins

  root 'login#index'


end

app/models/librarian.rb
class Librarian < ApplicationRecord
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } , uniqueness: true, presence: true
  validates :name, presence: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :library, presence: true
  has_secure_password validations: false
end

app/controllers/librarian_controller.rb
class LibrarianController < ApplicationController
    def index
    end

    def new
      @librarian = Librarian.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @librarian }
      end
    end

    def create
      @librarian = Librarian.new(librarian_params)
      if @librarian.save
        redirect_to librarian_login_url, alert: "Registration Successful, Please login!!"
      else
        redirect_to new_student_url, alert: "OOPS!! Problem Occurred. Please enter details again!"
      end
    end

    def show

    end

    def edit
      @librarian = Librarian.find(params[:id])
    end

    def update
      @librarian = Librarian.find(params[:id])
      respond_to do |format|
        if @librarian.update(librarian_params)
          format.html { render 'librarian/index', alert: 'Student successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @librarian.errors, status: :unprocessable_entity }
        end
      end

    end

    private
    def librarian_params
      params.require(:librarian).permit(:email, :name, :password, :library)
    end
  end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  def new
    @librarian = Librarian.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @librarian }
    end
  end

  def edit
    @librarian = Librarian.find(params[:id])
  end

  def fine
    @librarian = Librarian.find(session[:id])
    @finepay = HistoryRequest.where("fines > 0").where(:library_name=> @librarian.library)
    render "librarians/fine"
  end

  def update
    @librarian = Librarian.find(params[:id])
    respond_to do |format|
      if @librarian.update(email: params[:librarian][:email],name: params[:librarian][:name],password: params[:librarian][:password],library: params[:librarian][:library])
        format.html { render 'librarians/index', notice: 'Librarian was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action:"edit" }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  def admin_update_librarian
    @librarian = Librarian.find(params[:id])
    url = Rails.application.routes.recognize_path(request.referrer)   #fetch where the call is coming from
    last_controller = url[:controller]
    if last_controller == "librarians"
      update
    else
      @librarian = Librarian.find(params[:id])
      respond_to do |format|
      if @librarian.update(email: params[:librarian][:email],name: params[:librarian][:name],password: params[:librarian][:password],library: params[:librarian][:library])
        format.html { redirect_to admins_users_path, alert: 'Librarian was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action:"edit" }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
      end
  end

  def admin_show_librarian
    @librarian = Librarian.find(session[:id])
    respond_to do |format|
      format.html {render "librarians/show"}
      format.json { render json: @librarian }
    end
  end
  def show
    @librarian = Librarian.find(session[:id])
    @hold = HistoryRequest.where(:library_name=>@librarian.library,:status=>"Waiting for Approval")
    render "librarians/history_request"
  end

  def checkedout_request
    @librarian = Librarian.find(session[:id])
    @check_request = HistoryRequest.where(:library_name=>@librarian.library,:status=>"Checked Out")
    render "librarians/checkedout_request"
  end

  def borrow
    @librarian = Librarian.find(session[:id])
    @borrow = HistoryRequest.where(:library_name=>@librarian.library)
    render "librarians/borrow"
  end

  def books
    @books = Book.all
  end


  def index

  end

  def destroy
    bookid = params[:book_id]
    @book = Book.find(bookid)
    @book.destroy
    respond_to do |format|
      format.html { redirect_to librarians_path, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create
    @librarian = Librarian.new(librarian_params)
    @librarian.status= "no"
    if @librarian.save
      redirect_to librarians_login_url, alert: "Registration Successful, Please login!!"
    else
      redirect_to new_librarian_path, alert: "OOPS!! Problem Occurred. Please enter details again!"
    end
    end
  end




  private
  def librarian_params
    params.require(:librarian).permit(:email, :name, :password, :library)
  end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/views/librarians/_form.html.erb
<div class="msg">
  <ul>
    <% @librarian.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class="forms">
  <%= form_for @librarian do |form| %>

    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </p>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>

    <p>
      <%= form.label :library %>
      <%= select("librarian", "library", Library.all.collect{ |c| [ c.name] }) %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/librarians/admin_edit_librarian.html.erb
<div class="heading">
  <h1>Edit Librarian</h1></div>
</div>


<div class="msg">
  <ul>
    <% @librarian.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class="forms">
  <%= form_with scope: :librarian, url: admin_update_librarian_path, local: true do |form| %>
    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </p>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>

    <p>
      <%= form.label :library %>
      <%= select("librarian", "library", Library.all.collect{ |c| [ c.name] }) %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/librarians/books.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th scope="col">ISBN</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Language</th>
      <th scope="col">Published</th>
      <th scope="col">Edition</th>
      <th scope="col">Image</th>
      <th scope="col">Subject</th>
      <th scope="col">Summary</th>
      <th scope="col">Special?</th>
      <th scope="col">Delete</th>
      <th scope="col">Edit</th>
      <th scope="col">Show</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
     <% @books.each do |book| %>
       <tr>
         <td><%= book.isbn %></td>
         <td><%= book.title%></td>
         <td><%= book.author %></td>
         <td><%= book.language %></td>
         <td><%= book.published %></td>
         <td><%= book.edition %></td>
         <td><%= image_tag book.image.url(:thumb) %></td>
         <td><%= book.subject %></td>
         <td><%= book.summary %></td>
         <td><%= book.special %></td>
         <% @lib = Librarian.find(session[:id]) %>
         <% @library = Library.find_by_name(@lib.library) %>
         <% if @library.name == book.library %>
         <td><%= link_to 'Destroy', librarians_destroy_path(:book_id => book.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
           <% else %>
           <td></td>
           <%end %>
         <% if @library.name == book.library %>
         <td><%= link_to 'Edit', books_edit_path(:book_id => book.id) %></td>
         <% else %>
           <td></td>
         <%end %>
         <td><%= link_to 'Show', books_show_path(:book_id => book.id) %></td>
       </tr>
  <%end %>
  </tbody>
</table>
</body>

app/views/librarians/borrow.html.erb
<h1>Borrwed History</h1>

<table>
  <thead>
  <tr>
    <th scope="col">Student Name</th>
    <th scope="col">Student Email</th>
    <th scope="col">Library</th>
    <th scope="col">ISBN</th>
    <th scope="col">Status</th>
    <th scope="col">Time Checked out</th>
  </tr>
  </thead>

  <tbody>
  <% @borrow.each do |bor| %>
    <tr>
      <td><%= bor.student_name %></td>
      <td><%= bor.student_email %></td>
      <td><%= bor.library_name %></td>
      <td><%= bor.isbn%></td>
      <td><%= bor.status %></td>
      <td><%= bor.updated_at %></td>
    </tr>
  <%end %>
  </tbody>
</table>

app/views/librarians/checkedout_request.html.erb
<h1>Checkedout</h1>

<table>
  <thead>
  <tr>
    <th scope="col">Student Name</th>
    <th scope="col">Student Email</th>
    <th scope="col">Library</th>
    <th scope="col">ISBN</th>
    <th scope="col">Status</th>
    <th scope="col">Time Checked out</th>
  </tr>
  </thead>

  <tbody>
  <% @check_request.each do |check| %>
    <tr>
      <td><%= check.student_name %></td>
      <td><%= check.student_email %></td>
      <td><%= check.library_name %></td>
      <td><%= check.isbn%></td>
      <td><%= check.status %></td>
      <td><%= check.updated_at %></td>
    </tr>
  <%end %>
  </tbody>
</table>

app/views/librarians/edit.html.erb
<div class="heading">
  <h1>Edit Librarian</h1></div>
</div>


<div class="msg">
  <ul>
    <% @librarian.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class="forms">
  <%= form_with scope: :librarian, url: librarian_update_path, local: true do |form| %>
    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </p>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>

    <p>
      <%= form.label :library %>
      <%= select("librarian", "library", Library.all.collect{ |c| [ c.name] }) %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/librarians/fine.html.erb
<h1>Students With Overdue Fines</h1>

<table>
  <thead>
  <tr>
    <th scope="col">Library</th>
    <th scope="col">ISBN</th>
    <th scope="col">StudentName</th>
    <th scope="col">Fine</th>
  </tr>
  </thead>

  <tbody>
  <% @finepay.each do |h| %>
    <tr>
      <td><%= h.library_name %></td>
      <td><%= h.isbn%></td>
      <td><%= h.student_name %></td>
      <td><%= h.fines %></td>

    </tr>
  <%end %>
  </tbody>
</table>

app/views/librarians/history_request.html.erb
<h1>Hold Request</h1>

<table>
  <thead>
  <tr>
    <th scope="col">Student Name</th>
    <th scope="col">Student Email</th>
    <th scope="col">Library</th>
    <th scope="col">ISBN</th>
    <th scope="col">Status</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @hold.each do |hist| %>
    <tr>
      <td><%= hist.student_name %></td>
      <td><%= hist.student_email %></td>
      <td><%= hist.library_name %></td>
      <td><%= hist.isbn%></td>
      <td><%= hist.status %></td>
      <td><%= link_to 'Approve'%></td>
    </tr>
  <%end %>
  </tbody>
</table>

app/views/librarians/index.html.erb
<!DOCTYPE html>
<html lang="en">
<h1>Librarian DashBoard</h1>
  <body>
  <% @librarian = Librarian.find(session[:id]) %>
  <td><%= link_to "Books", librarians_books_path %></td><br>
  <td><%= link_to "View Hold Request", librarians_show_path%></td><br>
  <td><%= link_to "View Checkedout", librarians_checkedout_request_path%></td><br>
  <td><%= link_to "View BorrowingHistory", librarians_borrow_path%></td><br>
  <td><%= link_to 'Edit My profile', librarian_edit_path(session[:id]) %></td><br>
  <td><%= link_to 'Logout', sessions_destroy_path %></td><br>
  <td><%= link_to 'View Student Fines', librarians_fine_path%></td><br>
  <% @library = Library.find_by_name(@librarian.library) %>
  <td><%= link_to 'Edit Library', edit_library_path(@library) %></td><br>

  </body>
</html>

app/views/librarians/login.html.erb
<div class="heading">
  <h1>Librarians Login</h1></div>
</div>

<div class="msg">
  <% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
  <% end %>
</div>
<br>

<div class="forms">

  <%= form_with scope: :sessions, url: sessions_url, local:  true do |f| %>
    <p>
      <%=f.label :email %><br/>
      <%=f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>

    <%= f.submit :Login %><br>
    <br>

    <%= link_to 'New User Please Register here', librarians_new_path %>
  <% end %>

</div>

app/views/librarians/new.html.erb
<div class="heading">
  <h1>Librarian Registration </h1>
</div>

<div class="msg">
  <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
  <% end %>
</div>
<br>


<%= render 'librarians/form' %>

app/views/librarians/show.html.erb
<div class="heading">
  <h1>Librarian Profile</h1></div>
</div>

<div class="msg">
  <ul>
    <% @librarian.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class="forms">
  <%= form_for @librarian do |form| %>

    <p>
      <%= form.label :email %><br>
      <%= @librarian.email %>
    </p>

    <p>
      <%= form.label :name %><br>
      <%= @librarian.name %>
    </p>


    <p>
      <%= form.label :library %>
      <%= @librarian.library %>
    </p>

  <% end %>
</div>